exports.API_URL = "https://getbooks.onrender.com"
exports.BOOKS = "https://getbooks.onrender.com/books"
exports.CAT = "https://getbooks.onrender.com/cat"
exports.DELIVERY = "https://getbooks.onrender.com/delivery"
exports.USERS = "https://getbooks.onrender.com/users"